name: objectory
description: Object document mapper/persistency layer for server-side and browser apps
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/mongo_dart
version: 0.0.3
dependencies:
 unittest:
  sdk: unittest
 logging:
  sdk: logging
 args:
  sdk: args
 mongo_dart:
  git: git://github.com/vadimtsushko/mongo_dart.git
 lawndart:
  git: git://github.com/vadimtsushko/lawndart.git